### ISSUE TITLE
Python execute py script give me error

### ISSUE THREAD

**Issue by verticaio** [TetraTutorials/imdb_data_import_elastic#4]
# python imdb_actor_import.py 
Traceback (most recent call last):
  File "imdb_actor_import.py", line 105, in <module>
    main(buffer)
  File "imdb_actor_import.py", line 32, in main
    somelines = buffer.split('THE %s LIST' % listname)[1]
MemoryError

**Comment by verticaio** [comment]
I solve this issue increase ram size but this isn't solution. Right solution as here
https://stackoverflow.com/questions/13488746/memory-error-when-parsing-large-file-python
